apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ficsitmonitor

resources:
  - namespace.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - updater-cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ficsit-monitor
    includeSelectors: false
    includeTemplates: false
